### ISSUE TITLE
Demo portal at https://irischatgpt.streamlit.app/ no longer runs

### ISSUE THREAD

**Issue by isc-tstolker** [mwaseem75/irisChatGPT#6]
When opening the demo app, the following message is displayed:

> ImportError: This app has encountered an error. The original error message is redacted to prevent data leaks. Full error details have been recorded in the logs (if you're on Streamlit Cloud, click on 'Manage app' in the lower right of your app).
> Traceback:
> File "/home/adminuser/venv/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 535, in _run_script
>     exec(code, module.__dict__)
> File "/mount/src/streamlitllm/streamlitAPP.py", line 3, in <module>
>     import irisChatGPT
> File "/mount/src/streamlitllm/irisChatGPT.py", line 11, in <module>
>     from langchain import  SQLDatabase, SQLDatabaseChain

**Comment by mwaseem75** [comment]
Online demo has been removed from the repo
